// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DepartmentDialog: typeof import('./src/components/authority/DepartmentDialog.vue')['default']
    DepartmentList: typeof import('./src/components/authority/DepartmentList.vue')['default']
    EmailRegister: typeof import('./src/components/register/EmailRegister.vue')['default']
    IconBxBxLockAlt: typeof import('virtual:vite-icons/bx/bx-lock-alt')['default']
    IconCarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    IconIcBaselinePermIdentity: typeof import('virtual:vite-icons/ic/baseline-perm-identity')['default']
    IconIcOutlineFavorite: typeof import('virtual:vite-icons/ic/outline-favorite')['default']
    IconIcRoundAddCircleOutline: typeof import('virtual:vite-icons/ic/round-add-circle-outline')['default']
    IconIcRoundVisibility: typeof import('virtual:vite-icons/ic/round-visibility')['default']
    IconIcRoundVisibilityOff: typeof import('virtual:vite-icons/ic/round-visibility-off')['default']
    IconMdiAccount: typeof import('virtual:vite-icons/mdi/account')['default']
    IconMdiBeenhere: typeof import('virtual:vite-icons/mdi/beenhere')['default']
    IconMdiBookmark: typeof import('virtual:vite-icons/mdi/bookmark')['default']
    IconMdiChevronLeft: typeof import('virtual:vite-icons/mdi/chevron-left')['default']
    IconMdiNotificationClearAll: typeof import('virtual:vite-icons/mdi/notification-clear-all')['default']
    IconMdiReceipt: typeof import('virtual:vite-icons/mdi/receipt')['default']
    IconMdiSquareEditOutline: typeof import('virtual:vite-icons/mdi/square-edit-outline')['default']
    IconMdiStars: typeof import('virtual:vite-icons/mdi/stars')['default']
    IconMdiWaze: typeof import('virtual:vite-icons/mdi/waze')['default']
    LogDialog: typeof import('./src/components/system/LogDialog.vue')['default']
    PasswordResetDialog: typeof import('./src/components/authority/PasswordResetDialog.vue')['default']
    PhoneRegister: typeof import('./src/components/register/PhoneRegister.vue')['default']
    RoleDialog: typeof import('./src/components/authority/RoleDialog.vue')['default']
    RoleList: typeof import('./src/components/authority/RoleList.vue')['default']
    SlideDialog: typeof import('./src/components/captcha/SlideDialog.vue')['default']
    SlideVerify: typeof import('./src/components/captcha/SlideVerify.vue')['default']
    UserDialog: typeof import('./src/components/authority/UserDialog.vue')['default']
    UserList: typeof import('./src/components/authority/UserList.vue')['default']
    UsernameRegister: typeof import('./src/components/register/UsernameRegister.vue')['default']
  }
}

export { }
